### ISSUE TITLE
SSR error

### ISSUE THREAD

**Issue by revolunet** [betagouv/espace-membre-next#331]
Seen in logs

```
2024-07-16 12:54:33.607075364 +0200 CEST [web-1] Error: In order to get SSR working with tss-react you need to explicitly provide an Emotion cache.
2024-07-16 12:54:33.607086835 +0200 CEST [web-1] MUI users be aware: This is not an error strictly related to tss-react, with or without tss-react,
2024-07-16 12:54:33.607088241 +0200 CEST [web-1] MUI needs an Emotion cache to be provided for SSR to work.
2024-07-16 12:54:33.607089220 +0200 CEST [web-1] Here is the MUI documentation related to SSR setup: https://mui.com/material-ui/guides/server-rendering/
2024-07-16 12:54:33.607090161 +0200 CEST [web-1] TSS provides helper that makes the process of setting up SSR easier: https://docs.tss-react.dev/ssr
2024-07-16 12:54:33.607137853 +0200 CEST [web-1] at useCssAndCx (/app/.next/server/chunks/125.js:1:3446)
2024-07-16 12:54:33.607090638 +0200 CEST [web-1] at useCache (/app/.next/server/chunks/125.js:1:1885)
2024-07-16 12:54:33.607138639 +0200 CEST [web-1] at /app/.next/server/chunks/125.js:1:4379
2024-07-16 12:54:33.607139324 +0200 CEST [web-1] at m (/app/.next/server/chunks/3868.js:1:3323)
2024-07-16 12:54:33.607140540 +0200 CEST [web-1] at nj (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:46251)
2024-07-16 12:54:33.607141019 +0200 CEST [web-1] at nM (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47571)
2024-07-16 12:54:33.607141496 +0200 CEST [web-1] at nN (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
2024-07-16 12:54:33.607229091 +0200 CEST [web-1] at nN (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
2024-07-16 12:54:33.607142436 +0200 CEST [web-1] at nM (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:59102)
2024-07-16 12:54:33.607284228 +0200 CEST [web-1] at nM (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47717)
2024-07-16 12:54:33.607240631 +0200 CEST [web-1] at nM (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:61156)
2024-07-16 12:54:33.607284773 +0200 CEST [web-1] at nN (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
2024-07-16 12:54:33.607283155 +0200 CEST [web-1] at nN (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
2024-07-16 12:54:33.607306122 +0200 CEST [web-1] at nN (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64853)
2024-07-16 12:54:33.607283770 +0200 CEST [web-1] at nI (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:47010)
2024-07-16 12:54:33.607406562 +0200 CEST [web-1] at nD (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66680)
2024-07-16 12:54:33.607380335 +0200 CEST [web-1] at nB (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538)
2024-07-16 12:54:33.607352310 +0200 CEST [web-1] at nN (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
2024-07-16 12:54:33.607338856 +0200 CEST [web-1] at nM (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:58560)
2024-07-16 12:54:33.607407582 +0200 CEST [web-1] at nN (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64853) {
2024-07-16 12:54:33.607408146 +0200 CEST [web-1] digest: '1462358688'
2024-07-16 12:54:33.607352633 +0200 CEST [web-1] at nB (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538)
2024-07-16 12:54:33.607408686 +0200 CEST [web-1] }
2024-07-16 12:54:33.607353218 +0200 CEST [web-1] at nI (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:46965)
2024-07-16 12:54:33.607285197 +0200 CEST [web-1] at nB (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538)
2024-07-16 12:54:33.607376023 +0200 CEST [web-1] at nM (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:60937)
2024-07-16 12:54:33.607298681 +0200 CEST [web-1] at nD (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:66680)
2024-07-16 12:54:33.607336626 +0200 CEST [web-1] at nB (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:67538)
2024-07-16 12:54:33.607379596 +0200 CEST [web-1] at nN (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:64546)
2024-07-16 12:54:33.607353649 +0200 CEST [web-1] at nM (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:60862)
```

**Comment by revolunet** [comment]
fixed in https://github.com/betagouv/espace-membre-next/pull/332
